kotlin.code.style=official
org.gradle.jvmargs=-Xmx2G
org.gradle.warning.mode=all
# Check these on https://fabricmc.net/versions.html
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.160.7+26.3

# Mod Properties
mod_version=3.9.0-26.3
maven_group=de.jagenka
archives_base_name=diskordel
# Kotlin
fabric_kotlin_version=1.14.1+kotlin.2.4.20

